development:
  adapter: redis 
  url: redis://localhost:6379/1


test:
  adapter: test


production:
  adapter: redis
  url: <%= ENV.fetch("redis://:pcaaab2793fe3aa0e0ae093e46cfd8babd250db39062f43dfe09ca69bbfe1fce2@ec2-107-20-12-163.compute-1.amazonaws.com:18819") %>/<%= ENV.fetch("637") %>
  channel_prefix: peeps_platform_api_production


# production:
#   adapter: redis
#   url: <%= ENV.fetch("redis://127.0.0.1") %>/<%= ENV.fetch("6379") %>
#   channel_prefix: peeps_platform_api_production



# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: peeps_platform_api_production
