development:
  adapter: redis
  url: redis://localhost:6379/1


test:
  adapter: test


production:
  adapter: redis
  url: redistogo-deep-60008

  channel_prefix: peeps_platform_api_production



# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: peeps_platform_api_production
